### PR TITLE
Add a couple of starter unit tests.

### PR DESCRIPTION
**Pull request by audreyfeldroy**
Hey, thanks for writing cssmin!

In this pull request, I added a little test suite and a couple of starter unit tests:
- a test for remove_comments()
- a test for remove_unnecessary_whitespace().

Is this helpful, and if so, do you want more tests for the rest of cssmin? I'm happy to write more if you want.

Or if this needs work/edits, let me know what to fix and I'll try my best :)

### CODE REVIEW

**Comment by audreyfeldroy** [comment]
@zacharyvoase Ping, I guess you didn't see this.

**Comment by zacharyvoase** [comment]
I deliberately didn’t add unit tests for the CSS minification because it’s based on YUI’s minifier. But this project is currently unmaintained—if you want I can just give you the repo? :)

**Comment by audreyfeldroy** [comment]
Sure, that would be great, I'd love to maintain it :)

**Comment by albertyw** [comment]
@zacharyvoase I'd also like to see this repository be moved to an owner who can maintain it, either @audreyr or I would personally recommend https://github.com/jazzband

**Comment by zacharyvoase** [comment]
I think cssmin as it is currently implemented shouldn't be used. It's just a set of regexes that worked pretty well on the CSS of 3+ years ago, but given the syntactic advances of the last few years, you really should use a modern front-end asset pipeline (especially one that is actively maintained).

**Pull request closed without merging**
