### PR TITLE
Add classifiers to setup.py.

### PR DESCRIPTION
**Pull request by berkerpeksag**

### CODE REVIEW

**Comment by jodal** [comment]
To add some motivation to this pull request:

Adding Trove classifiers to setup.py would for example make https://requires.io list cssmin as Python 3 compatible, and thus not make projects using cssmin think that they need to replace it for moving to Python 3.

**Comment by berkerpeksag** [comment]
@zacharyvoase, is there anything I can do to move this issue forward? Thanks!

**Comment by jodal** [comment]
Why was this issue closed? It's trivial to fix, and hasn't been.

**Comment by zacharyvoase** [comment]
I'm no longer supporting cssmin; it was a basic port of the YUI css compressor to Python but the state-of-the-art has since moved on and I don't have enough time to maintain it, especially considering the number of feature requests for more advanced CSS3-aware behavior. I suggest you use the original YUI Compressor or use one of the many nodejs minifiers available today. Sorry about this.

**Pull request closed without merging**
